config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins, path: 'admin',
              path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up: 'signup' }

  devise_scope :admin do
    get '/admin/password', to: 'admins#edit', as: 'edit_admin_password'
    put '/admin/password_change', to: 'admins#update', as: 'change_admin_password'
  end

  root 'main#index'

  resources :posts
  resources :tags, except: :show
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :lockable, :timeoutable

  validates_presence_of :password
  validates_confirmation_of :password
end

app/models/post.rb
# encoding: utf-8
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags

  validates_presence_of :title, :body

  validate :presence_tags

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

private

  def presence_tags
    if tags.blank?
      errors.add(:base, 'Você deve selecionar pelo menos uma tag') unless Tag.all.count < 1
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates_presence_of :name

  def to_s
    name
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def edit
    @admin = current_admin
  end

  def update
    @admin = Admin.find(current_admin.id)
    if @admin.update(admin_params)
      sign_in @admin, bypass: true
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def admin_params
    params.require(:admin).permit(:password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: t('flash.crud.create.notice', resource: t('activerecord.models.post'))
    else
      render 'new', alert: t('flash.tag.create.alert', resource: t('activerecord.models.tag').downcase)
    end
  end

  def update
    @post.slug = nil  # !!!
    if @post.update(post_params)
      redirect_to @post, notice: t('flash.crud.update.notice', resource: t('activerecord.models.post'))
    else
      render 'edit', alert: t('flash.tag.update.alert', resource: t('activerecord.models.tag').downcase)
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: t('flash.crud.delete.notice', resource: t('activerecord.models.post'))
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :published, tag_ids: [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: t('flash.crud.create.notice', resource: t('activerecord.models.tag'))
    else
      render :new, alert: t('flash.crud.create.alert', resource: t('activerecord.models.tag').downcase)
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: t('flash.crud.update.notice', resource: t('activerecord.models.tag'))
    else
      render :edit, alert: t('flash.crud.update.alert', resource: t('activerecord.models.tag').downcase)
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_url, notice: t('flash.crud.destroy.notice', resource: t('activerecord.models.tag'))
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_explanation(resource)
    if resource.errors.any?
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

      html = <<-HTML
      <div id=''>
        <h3>#{ I18n.t 'form.error.message' }</h3>
        <ul>#{ messages }</ul>
      </div>
      HTML

      html.html_safe
    end
  end
end

app/views/admins/edit.html.slim
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      h2.text-center.page-header Change Password

      .form= form_for(@admin, url: change_admin_password_path, method: :put) do |f|
        - if @admin.errors.any?
          .alert.alert-danger
            - @admin.errors.full_messages.each do |msg|
              span= msg

        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control', disabled: true

        .form-group
          = f.label :password
          = f.password_field :password, autofocus: true, autocomplete: 'off', class: 'form-control'

        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control'

        .form-group
          = f.submit 'Change password', class: 'btn btn-primary btn-lg btn-block'

app/views/layouts/application.html.slim
DOCTYPE html
html lang='pt-BR'
  head
    meta charset='utf-8'
    title= content_for?(:title) ? yield(:title) : 'Blog - Rafael Belo'
    = stylesheet_link_tag 'application'
    = csrf_meta_tags

  body
    = render 'shared/navbar'

    - if alert.present?
      .alert.alert-danger role='alert'
        = alert

    - if notice.present?
      .alert.alert-info role='notice'
        = notice

    = yield

    = javascript_include_tag 'application'
    = yield :javascript if content_for?(:javascript)

app/views/main/index.html.slim
h2 Hello Blog

app/views/posts/_form.html.slim
.form
  = form_for(@post) do |f|
    = errors_explanation(@post)

    .form-group
      = f.label :tag
      = collection_check_boxes :post, :tag_ids, Tag.all, :id, :name

    .form-group
      = f.label :published
      = f.check_box :published

    .form-group
      = f.label :title, t('form.labels.title')
      = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :body, t('form.labels.body')
      = f.text_area :body, class: 'ckeditor'

    br
    .form-group
      = f.submit t('form.action.submit', resource: 'post'), class: 'btn btn-primary'

app/views/posts/edit.html.slim
.container-fluid
  .row
    .col-md-12
      h2= t('title.post.edit')

      = render 'form'

      = link_to t('link.action.back'), posts_path, class: 'button'

app/views/posts/index.html.slim
.container-fluid
  .row
    .col-md-12.col-xs-12
      =notice

      h2= t('title.post.index')

      table.table.table-bordered.table-hover
        thead
          tr
            th Title
            th Tag
            th Published?
            th.text-center colspan='3' Ações

        tbody
          - @posts.each do |post|
            tr
              td= post.title
              td= post.tags.any? ? post.tags.join(' ') : "<span class='text-mutted'>Post sem tag</span>".html_safe
              td= post.published
              td= link_to t('link.action.show'), post
              td= link_to t('link.action.edit'), edit_post_path(post)
              td= link_to t('link.action.destroy'), post, method: :delete,
                data: { confirm: t('data.confirm.destroy', resource: 'post') }

      = link_to t('link.action.new', resource: 'post'), new_post_path, class: 'btn btn-primary'
      '&nbsp;
      = link_to t('link.action.back').capitalize, root_path, class: 'btn btn-default'

app/views/posts/new.html.slim
.container-fluid
  .row
    .col-md-12
      h2= t('title.post.new')

      = render 'form'

      = link_to t('link.action.back'), posts_path, class: 'button-negative'

app/views/posts/show.html.slim
.container-fluid
  .row
    .col-md-10.col-md-offset-1
      = notice

      h1= @post.title

      - @post.tags.each do |tag|
          small= tag


      p= @post.created_at

      p= @post.body.html_safe

      = link_to t('link.action.back'), posts_path

app/views/shared/_navbar.html.slim
.navbar.navbar-default.navbar-static-top role='navigation'
  .container-fluid
    / Put into navbar-header toogle for mobile
    .navbar-header
      = link_to 'Blog', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li class='#{controller_name == 'posts' ? 'active' : '' }'
          = link_to 'Posts', posts_path
        li class='#{controller_name == 'tags' ? 'active' : '' }'
          = link_to 'Tags', tags_path

      - if admin_signed_in?
        ul.nav.navbar-nav.navbar-right
          li.dropdown
            = link_to "#{current_admin.email} <span class='caret'></span>".html_safe, '#',
                      data: { toggle: 'dropdown' }, class: 'dropdown-toggle'
            ul.dropdown-menu role='menu'
              li= link_to 'Change password', edit_admin_password_path
              li.divider
              li= link_to 'Logout', destroy_admin_session_path, method: :delete

app/views/tags/_form.html.slim
.form-inline role='form'
  = form_for(@tag) do |f|
    = errors_explanation(@tag)

    br
    .form-group
      = f.label :name
      '&nbsp;
      = f.text_field :name, class: 'form-control'
      '&nbsp;

    .form-group
      = f.submit t('form.action.submit', resource: 'tag'), class: 'btn btn-primary'

app/views/tags/edit.html.slim
.container-fluid
  .row
    .col-md-12

      h2= t('title.tag.edit')
      = render 'form'
      = link_to t('link.action.back'), tags_path, class: 'button'

app/views/tags/index.html.slim
.container-fluid
  .row
    .col-md-12

      = notice

      h2= t('title.tag.index')

      table.table.table-bordered.table-hover
        thead
          tr
            th Name
            th.text-center colspan='2' Ações

        tbody
          - @tags.each do |tag|
            tr
              td= tag.name
              td= link_to t('link.action.edit'), edit_tag_path(tag)
              td= link_to t('link.action.destroy'), tag, method: :delete,
                data: { confirm: t('data.confirm.destroy', resource: 'tag') }

      = link_to t('link.action.new', resource: 'tag'), new_tag_path, class: 'btn btn-primary'
      '&nbsp;
      = link_to t('link.action.back').capitalize, root_path, class: 'btn btn-default'

app/views/tags/new.html.slim
.container-fluid
  .row
    .col-md-12

      h2= t('title.tag.new')
      = render 'form'
      = link_to t('link.action.back'), tags_path, class: 'button-negative'